[pytest]
addopts = -ra --capture=tee-sys
testpaths = tests
python_files = verify.py u_boot.py linux_boot.py test_*.py
python_functions = test_* u_boot linux_boot
markers =
    uboot: U-Boot related tests
    linux: Linux boot related tests
    smoke: basic smoke tests
